; Explanation of parameters between the first two colons(::)
; {Space}: Output after you enter a {Space}
; c: Case sensitive
; ?: Don't care what you type before the trigger
; T: Output text immediately instead of sending the keystroke
; o: Delete the {Space} you entered

: c?To:\!::¡
: c?To:\#::♯
: c?To:\&::⅋
: c?To:\*::⋆
: c?To:\+::⊹
: c?To:\-::⁻¹
: c?To:\.::·
: c?To:\/::⧸
: c?To:\0::₀
: c?To:\1::₁
: c?To:\2::₂
: c?To:\3::₃
: c?To:\4::₄
: c?To:\5::₅
: c?To:\6::₆
: c?To:\7::₇
: c?To:\8::₈
: c?To:\9::₉
: c?To:\:::∶
: c?To:\<::⟨
: c?To:\=::≠
: c?To:\>::⟩
: c?To:\?::¿
: c?To:\A::𝔸
: c?To:\B::□
: c?To:\C::ℂ
: c?To:\D::Δ
: c?To:\E::Η
: c?To:\F::𝔽
: c?To:\G::Γ
: c?To:\H::ℍ
: c?To:\I::⋂
: c?To:\J::⨆
: c?To:\K::𝕂
: c?To:\L::Λ
: c?To:\N::ℕ
: c?To:\O::Ø
: c?To:\P::Π
: c?To:\Q::ℚ
: c?To:\R::ℝ
: c?To:\S::Σ
: c?To:\T::◀
: c?To:\U::⋃
: c?To:\V::‖
: c?To:\X::⨯
: c?To:\Y::Ϳ
: c?To:\Z::ℤ
; : c?To:\:::∶
; TODO: fix this
: c?To:\a::α
: c?To:\b::β
: c?To:\c::χ
: c?To:\d::↓
: c?To:\e::ε
: c?To:\f::‹
: c?To:\g::γ
: c?To:\h::⟶
: c?To:\i::∩
: c?To:\j::⊔
: c?To:\k::κ
: c?To:\l::←
: c?To:\m::μ
: c?To:\n::¬
: c?To:\o::∘
: c?To:\p::Π
: c?To:\q::∎
: c?To:\r::→
: c?To:\s::σ
: c?To:\t::▸
: c?To:\u::↑
: c?To:\v::∨
: c?To:\w::℘
: c?To:\x::×
: c?To:\y::¥
: c?To:\z::ζ
: c?To:\|::∣
: c?To:\~::∼
: c?To:\^(::⁽
: c?To:\^)::⁾
: c?To:\^+::⁺
: c?To:\^-::⁻
: c?To:\^0::⁰
: c?To:\^1::¹
: c?To:\^2::²
: c?To:\^3::³
: c?To:\^4::⁴
: c?To:\^5::⁵
: c?To:\^6::⁶
: c?To:\^7::⁷
: c?To:\^8::⁸
: c?To:\^9::⁹
: c?To:\^=::⁼
: c?To:\^A::ᴬ
: c?To:\^B::ᴮ
: c?To:\^D::ᴰ
: c?To:\^E::ᴱ
: c?To:\^G::ᴳ
: c?To:\^H::ᴴ
: c?To:\^I::ᴵ
: c?To:\^J::ᴶ
: c?To:\^K::ᴷ
: c?To:\^L::ᴸ
: c?To:\^M::ᴹ
: c?To:\^N::ᴺ
: c?To:\^O::ᴼ
: c?To:\^P::ᴾ
: c?To:\^R::ᴿ
: c?To:\^T::ᵀ
: c?To:\^U::ᵁ
: c?To:\^V::ⱽ
: c?To:\^W::ᵂ
: c?To:\^a::ᵃ
: c?To:\^b::ᵇ
: c?To:\^c::ᶜ
: c?To:\^d::ᵈ
: c?To:\^e::ᵉ
: c?To:\^f::ᶠ
: c?To:\^g::ᵍ
: c?To:\^h::ʰ
: c?To:\^i::ⁱ
: c?To:\^j::ʲ
: c?To:\^k::ᵏ
: c?To:\^l::ˡ
: c?To:\^m::ᵐ
: c?To:\^n::ⁿ
: c?To:\^o::ᵒ
: c?To:\^p::ᵖ
: c?To:\^r::ʳ
: c?To:\^s::ˢ
: c?To:\^t::ᵗ
: c?To:\^u::ᵘ
: c?To:\^v::ᵛ
: c?To:\^w::ʷ
: c?To:\^x::ˣ
: c?To:\^y::ʸ
: c?To:\^z::ᶻ
: c?To:\_(::₍
: c?To:\_)::₎
: c?To:\_+::₊
: c?To:\_-::₋
: c?To:\_0::₀
: c?To:\_1::₁
: c?To:\_2::₂
: c?To:\_3::₃
: c?To:\_4::₄
: c?To:\_5::₅
: c?To:\_6::₆
: c?To:\_7::₇
: c?To:\_8::₈
: c?To:\_9::₉
: c?To:\_=::₌
: c?To:\_a::ₐ
: c?To:\_e::ₑ
: c?To:\_h::ₕ
: c?To:\_i::ᵢ
: c?To:\_j::ⱼ
: c?To:\_k::ₖ
: c?To:\_l::ₗ
: c?To:\_m::ₘ
: c?To:\_n::ₙ
: c?To:\_o::ₒ
: c?To:\_p::ₚ
: c?To:\_r::ᵣ
: c?To:\_s::ₛ
: c?To:\_t::ₜ
: c?To:\_u::ᵤ
: c?To:\_v::ᵥ
: c?To:\_x::ₓ
: c?To:\Al::Α
: c?To:\An::⋀
: c?To:\Be::Β
: c?To:\Bo::□
: c?To:\Bu::≎
: c?To:\Ca::⋒
: c?To:\Ch::Χ
: c?To:\Co::ℂ
: c?To:\Cu::⋓
: c?To:\De::Ϯ
: c?To:\Di::Ϝ
: c?To:\Do::⇓
: c?To:\Ep::Ε
: c?To:\Et::Η
: c?To:\Fe::Ϥ
: c?To:\Fr::☹
: c?To:\Ga::α
: c?To:\Gb::β
: c?To:\Gc::χ
: c?To:\Gd::δ
: c?To:\Ge::ε
: c?To:\Gf::φ
: c?To:\Gg::γ
: c?To:\Gi::ι
: c?To:\Gk::κ
: c?To:\Gl::λ
: c?To:\Gm::μ
: c?To:\Gn::ν
: c?To:\Go::ω
: c?To:\Gp::ψ
: c?To:\Gr::ρ
: c?To:\Gs::σ
: c?To:\Gt::τ
: c?To:\Gu::υ
: c?To:\Gx::ξ
: c?To:\Gz::ζ
: c?To:\He::Ͱ
: c?To:\Ho::Ϩ
: c?To:\Im::ℑ
: c?To:\In::ℤ
: c?To:\Io::Ι
: c?To:\Jo::⨆
: c?To:\Ka::Κ
: c?To:\Kh::Ϧ
: c?To:\Ko::Ϟ
: c?To:\La::Λ
: c?To:\Le::✉
: c?To:\Ll::⋘
: c?To:\Lo::⇐
: c?To:\Ls::↰
: c?To:\Lu::⨆
: c?To:\Me::⨅
: c?To:\Na::ℕ
: c?To:\Nu::Ν
: c?To:\Om::Ω
: c?To:\Or::⋁
: c?To:\Ox::⨂
: c?To:\Ph::Φ
: c?To:\Pi::Π
: c?To:\Ps::Ψ
: c?To:\Ra::ℚ
: c?To:\Re::ℜ
: c?To:\Rh::Ρ
: c?To:\Ri::⇒
: c?To:\Rr::⇛
: c?To:\Rs::↱
: c?To:\Sa::Ϻ
: c?To:\Sh::Ϸ
: c?To:\Si::Σ
: c?To:\Sm::☺
: c?To:\Sq::⨅
: c?To:\St::Ϛ
: c?To:\Su::⨆
: c?To:\Ta::Τ
: c?To:\Tb::◀
: c?To:\Th::Θ
: c?To:\Tr::◀
: c?To:\Tw::◁
: c?To:\Un::⋃
: c?To:\Up::Υ
: c?To:\Vd::⊩
: c?To:\Ve::‖
: c?To:\Vv::⊪
: c?To:\Xi::Ξ
: c?To:\Yo::Ϳ
: c?To:\Ze::Ζ
: c?To:\aa::å
: c?To:\ae::æ
: c?To:\af::؋
: c?To:\al::∀
: c?To:\am::∐
: c?To:\an::∧
: c?To:\ap::⌶
: c?To:\as::∗
: c?To:\au::₳
: c?To:\av::⨍
: c?To:\ba::∽
: c?To:\be::β
: c?To:\bi::⇔
: c?To:\bl::▪
: c?To:\bo::⊥
: c?To:\bu::•
: c?To:\bx::⊠
: c?To:\bz::ℤ
: c?To:\ca::∩
: c?To:\cc::ç
: c?To:\cd::⬝
: c?To:\ce::ȩ
: c?To:\ch::χ
: c?To:\ci::●
: c?To:\cl::⌞
: c?To:\co::⬝
: c?To:\cr::₢
: c?To:\cu::⌜
: c?To:\da::†
: c?To:\dd::↡
: c?To:\de::δ
: c?To:\dh::ð
: c?To:\di::◆
: c?To:\dl::↙
: c?To:\do::⬝
: c?To:\dr::↘
: c?To:\dv::∣
: c?To:\dz::↯
: c?To:\el::ℓ
: c?To:\em::—
: c?To:\en::–
: c?To:\ep::ε
: c?To:\et::η
: c?To:\eu::€
: c?To:\ex::∃
: c?To:\fa::℻
: c?To:\fe::ϥ
: c?To:\fl::‹
: c?To:\fo::∀
: c?To:\fr::›
: c?To:\fu::λ
: c?To:\ga::γ
: c?To:\ge::≥
: c?To:\gg::≫
: c?To:\gi::ℷ
: c?To:\gl::⊓
: c?To:\gn::≩
: c?To:\go::⊢
: c?To:\gr::‘
: c?To:\gt::⋗
: c?To:\gu::₲
: c?To:\gv::≩
: c?To:\hb::ℏ
: c?To:\hc::◫
: c?To:\he::ͱ
: c?To:\hi::⇨
: c?To:\hn::￢
: c?To:\ho::⟶
: c?To:\hr::₴
: c?To:\if::↔
: c?To:\im::→
: c?To:\in::∈
: c?To:\io::ι
: c?To:\is::≅
: c?To:\jo::⊔
: c?To:\ka::κ
: c?To:\ke::K
: c?To:\kh::ϧ
: c?To:\ki::į
: c?To:\ko::ϟ
: c?To:\la::λ
: c?To:\lb::⟅
: c?To:\lc::⌈
: c?To:\ld::“
: c?To:\le::≤
: c?To:\lf::⌊
: c?To:\lh::◁
: c?To:\li::₤
: c?To:\ll::≪
: c?To:\ln::≨
: c?To:\lo::✧
: c?To:\lq::‘
: c?To:\lr::↔
: c?To:\lt::⋉
: c?To:\lu::⊔
: c?To:\lv::≨
: c?To:\ma::♂
: c?To:\me::∈
: c?To:\mh::℧
: c?To:\mi::∣
: c?To:\mp::∓
: c?To:\mu::μ
: c?To:\na::ℕ
: c?To:\nb::𝓝
: c?To:\ne::≠
: c?To:\nh::𝓝
: c?To:\ni::∋
: c?To:\nm::∤
: c?To:\nn::∌
: c?To:\no::¬
: c?To:\np::⊀
: c?To:\nr::↛
: c?To:\ns::≁
: c?To:\nt::⋪
: c?To:\nu::ν
: c?To:\nv::⊭
: c?To:\nw::↖
: c?To:\oc::🛑
: c?To:\oe::œ
: c?To:\oh::Ω
: c?To:\oi::∮
: c?To:\om::ω
: c?To:\oo::⊚
: c?To:\or::∨
: c?To:\os::⊘
: c?To:\ot::⊗
: c?To:\ou::℥
: c?To:\ox::⊗
: c?To:\pa::▰
: c?To:\pd::∂
: c?To:\pe::⅌
: c?To:\ph::φ
: c?To:\pi::π
: c?To:\pm::±
: c?To:\po::£
: c?To:\pr::↣
: c?To:\ps::ψ
: c?To:\qe::∎
: c?To:\rc::⌉
: c?To:\rd::”
: c?To:\re::▬
: c?To:\rf::⌋
: c?To:\rh::ρ
: c?To:\ri::﷼
: c?To:\ro::√
: c?To:\rq::’
: c?To:\rr::↠
: c?To:\rt::⋊
: c?To:\ru::₽
: c?To:\sa::ϻ
: c?To:\sb::﹨
: c?To:\se::§
: c?To:\sh::ϸ
: c?To:\si::σ
: c?To:\sm::•
: c?To:\sp::₷
: c?To:\sq::◾
: c?To:\ss::⊆
: c?To:\st::⋆
: c?To:\su::⊆
: c?To:\sw::↙
: c?To:\ta::τ
: c?To:\tb::◂
: c?To:\te::₸
: c?To:\th::θ
: c?To:\ti::⁀
: c?To:\to::→
: c?To:\tr::⬝
: c?To:\tu::₮
: c?To:\tw::◃
: c?To:\ud::↕
: c?To:\ul::↖
: c?To:\un::∪
: c?To:\up::⊎
: c?To:\ur::↗
: c?To:\uu::↟
: c?To:\va::ϖ
: c?To:\vc::č
: c?To:\vd::ď
: c?To:\ve::ě
: c?To:\vs::ς
: c?To:\wa::⚠
: c?To:\wc::⩿
: c?To:\we::∧
: c?To:\wo::₩
: c?To:\wp::℘
: c?To:\wr::≀
: c?To:\xi::ξ
: c?To:\ye::¥
: c?To:\ze::ζ
: c?To:\alpha::α
: c?To:\beta::β
: c?To:\gamma::γ
: c?To:\delta::δ
: c?To:\epsilon::ε
: c?To:\zeta::ζ
: c?To:\eta::η
: c?To:\theta::θ
: c?To:\vartheta::ϑ
: c?To:\iota::ι
: c?To:\kappa::κ
: c?To:\lambda::λ
: c?To:\omicron::ο
: c?To:\varpi::ϖ
: c?To:\rho::ρ
: c?To:\varrho::ϱ
: c?To:\sigma::σ
: c?To:\tau::τ
: c?To:\upsilon::υ
: c?To:\phi::φ
: c?To:\varphi::ϕ
: c?To:\psi::ψ
: c?To:\omega::ω
: c?To:\Alpha::Α
: c?To:\Beta::Β
: c?To:\Gamma::Γ
: c?To:\Delta::Δ
: c?To:\Epsilon::Ε
: c?To:\Zeta::Ζ
: c?To:\Eta::Η
: c?To:\Theta::Θ
: c?To:\Iota::Ι
: c?To:\Kappa::Κ
: c?To:\Lambda::Λ
: c?To:\Omicron::Ο
: c?To:\Rho::Ρ
: c?To:\Sigma::Σ
: c?To:\Tau::Τ
: c?To:\Upsilon::Υ
: c?To:\Phi::Φ
: c?To:\Psi::Ψ
: c?To:\Omega::Ω
: c?To:\partial::∂
: c?To:\hbar::ℏ
: c?To:\times::×
: c?To:\cross::×
: c?To:\div::÷
: c?To:\cdot::⬝
: c?To:\mid::∣
: c?To:\nmid::∤
: c?To:\cdots::⋯
: c?To:\vdots::⋮
: c?To:\ddots::⋱
: c?To:\forall::∀
: c?To:\exist::∃
: c?To:\nexist::∄
: c?To:\not::¬
: c?To:\sube::⊆
: c?To:\leftarrow::←
: c?To:\rightarrow::→
: c?To:\uparrow::↑
: c?To:\downarrow::↓
: c?To:\upleftarrow::↖
: c?To:\uprightarrow::↗
: c?To:\downleftarrow::↙
: c?To:\downrightarrow::↘
: c?To:\leftrightarrow::↔
: c?To:\mapsto::↦
: c?To:\Rightarrow::⇒
: c?To:\Leftarrow::⇐
: c?To:\Leftrightarrow::⇔
: c?To:\hookrightarrow::↪
: c?To:\:=::≔
: c?To:\norm::‖
: c?To:\infty::∞
: c?To:\langle::⟨
: c?To:\rangle::⟩
: c?To:\lceil::⌈
: c?To:\lfloor::⌊
: c?To:\rceil::⌉
: c?To:\rfloor::⌋
: c?To:\sqrt::√
: c?To:\cbrt::∛
: c?To:\int::∫
: c?To:\iint:::∬
: c?To:\iiint::∭
: c?To:\oint::∮
: c?To:\oiint::∯
: c?To:\oiiint::∰
: c?To:\nabla::∇
: c?To:\grad::∇
: c?To:\cap::∩
: c?To:\cup::∪
: c?To:\comp::∘
: c?To:\circ::∘
: c?To:\star::⋆
: c?To:\boxtimes::⊠
: c?To:\oplus::⊕
: c?To:\otimes::⊗
: c?To:\and::∧
: c?To:\wedge::∧
: c?To:\vee::∨
: c?To:\neg::¬
: c?To:\sim::∼
: c?To:\cong::≅
: c?To:\square::◾
: c?To:\parallelogram::▰
: c?To:\triangle::▵
: c?To:\qed::∎
: c?To:\diamond::◆
: c?To:\Smile::☺
: c?To:\Frowny::☹
: c?To:\frac12::½
: c?To:\frac13::⅓
: c?To:\frac23::⅔
: c?To:\frac14::¼
: c?To:\frac34::¾
: c?To:\frac15::⅕
: c?To:\frac25::⅖
: c?To:\frac35::⅗
: c?To:\frac45::⅘
: c?To:\frac16::⅙
: c?To:\frac56::⅚
: c?To:\frac18::⅛
: c?To:\frac38::⅜
: c?To:\frac58::⅝
: c?To:\frac78::⅞
: c?To:\bbA::𝔸
: c?To:\bbB::𝔹
: c?To:\bbC::ℂ
: c?To:\bbD::𝔻
: c?To:\bbE::𝔼
: c?To:\bbF::𝔽
: c?To:\bbG::𝔾
: c?To:\bbH::ℍ
: c?To:\bbI::𝕀
: c?To:\bbJ::𝕁
: c?To:\bbK::𝕂
: c?To:\bbL::𝕃
: c?To:\bbM::𝕄
: c?To:\bbN::ℕ
: c?To:\bbO::𝕆
: c?To:\bbP::ℙ
: c?To:\bbQ::ℚ
: c?To:\bbR::ℝ
: c?To:\bbS::𝕊
: c?To:\bbT::𝕋
: c?To:\bbU::𝕌
: c?To:\bbV::𝕍
: c?To:\bbW::𝕎
: c?To:\bbX::𝕏
: c?To:\bbY::𝕐
: c?To:\bbZ::ℤ
: c?To:\bba::𝕒
: c?To:\bbb::𝕓
: c?To:\bbc::𝕔
: c?To:\bbd::𝕕
: c?To:\bbe::𝕖
: c?To:\bbf::𝕗
: c?To:\bbg::𝕘
: c?To:\bbh::𝕙
: c?To:\bbi::𝕚
: c?To:\bbj::𝕛
: c?To:\bbk::𝕜
: c?To:\bbl::𝕝
: c?To:\bbm::𝕞
: c?To:\bbn::𝕟
: c?To:\bbo::𝕠
: c?To:\bbp::𝕡
: c?To:\bbq::𝕢
: c?To:\bbr::𝕣
: c?To:\bbs::𝕤
: c?To:\bbt::𝕥
: c?To:\bbu::𝕦
: c?To:\bbv::𝕧
: c?To:\bbw::𝕨
: c?To:\bbx::𝕩
: c?To:\bby::𝕪
: c?To:\bbz::𝕫
: c?To:\bfA::𝐀
: c?To:\bfB::𝐁
: c?To:\bfC::𝐂
: c?To:\bfD::𝐃
: c?To:\bfE::𝐄
: c?To:\bfF::𝐅
: c?To:\bfG::𝐆
: c?To:\bfH::𝐇
: c?To:\bfI::𝐈
: c?To:\bfJ::𝐉
: c?To:\bfK::𝐊
: c?To:\bfL::𝐋
: c?To:\bfM::𝐌
: c?To:\bfN::𝐍
: c?To:\bfO::𝐎
: c?To:\bfP::𝐏
: c?To:\bfQ::𝐐
: c?To:\bfR::𝐑
: c?To:\bfS::𝐒
: c?To:\bfT::𝐓
: c?To:\bfU::𝐔
: c?To:\bfV::𝐕
: c?To:\bfW::𝐖
: c?To:\bfX::𝐗
: c?To:\bfY::𝐘
: c?To:\bfZ::𝐙
: c?To:\bfa::𝐚
: c?To:\bfb::𝐛
: c?To:\bfc::𝐜
: c?To:\bfd::𝐝
: c?To:\bfe::𝐞
: c?To:\bff::𝐟
: c?To:\bfg::𝐠
: c?To:\bfh::𝐡
: c?To:\bfi::𝐢
: c?To:\bfj::𝐣
: c?To:\bfk::𝐤
: c?To:\bfl::𝐥
: c?To:\bfm::𝐦
: c?To:\bfn::𝐧
: c?To:\bfo::𝐨
: c?To:\bfp::𝐩
: c?To:\bfq::𝐪
: c?To:\bfr::𝐫
: c?To:\bfs::𝐬
: c?To:\bft::𝐭
: c?To:\bfu::𝐮
: c?To:\bfv::𝐯
: c?To:\bfw::𝐰
: c?To:\bfx::𝐱
: c?To:\bfy::𝐲
: c?To:\bfz::𝐳
: c?To:\itA::𝘈
: c?To:\itB::𝘉
: c?To:\itC::𝘊
: c?To:\itD::𝘋
: c?To:\itE::𝘌
: c?To:\itF::𝘍
: c?To:\itG::𝘎
: c?To:\itH::𝘏
: c?To:\itI::𝘐
: c?To:\itJ::𝘑
: c?To:\itK::𝘒
: c?To:\itL::𝘓
: c?To:\itM::𝘔
: c?To:\itN::𝘕
: c?To:\itO::𝘖
: c?To:\itP::𝘗
: c?To:\itQ::𝘘
: c?To:\itR::𝘙
: c?To:\itS::𝘚
: c?To:\itT::𝘛
: c?To:\itU::𝘜
: c?To:\itV::𝘝
: c?To:\itW::𝘞
: c?To:\itX::𝘟
: c?To:\itY::𝘠
: c?To:\itZ::𝘡
: c?To:\ita::𝘢
: c?To:\itb::𝘣
: c?To:\itc::𝘤
: c?To:\itd::𝘥
: c?To:\ite::𝘦
: c?To:\itf::𝘧
: c?To:\itg::𝘨
: c?To:\ith::𝘩
: c?To:\iti::𝘪
: c?To:\itj::𝘫
: c?To:\itk::𝘬
: c?To:\itl::𝘭
: c?To:\itm::𝘮
: c?To:\itn::𝘯
: c?To:\ito::𝘰
: c?To:\itp::𝘱
: c?To:\itq::𝘲
: c?To:\itr::𝘳
: c?To:\its::𝘴
: c?To:\itt::𝘵
: c?To:\itu::𝘶
: c?To:\itv::𝘷
: c?To:\itw::𝘸
: c?To:\itx::𝘹
: c?To:\ity::𝘺
: c?To:\itz::𝘻
: c?To:\MiA::𝐴
: c?To:\MiB::𝐵
: c?To:\MiC::𝐶
: c?To:\MiD::𝐷
: c?To:\MiE::𝐸
: c?To:\MiF::𝐹
: c?To:\MiG::𝐺
: c?To:\MiH::𝐻
: c?To:\MiI::𝐼
: c?To:\MiJ::𝐽
: c?To:\MiK::𝐾
: c?To:\MiL::𝐿
: c?To:\MiM::𝑀
: c?To:\MiN::𝑁
: c?To:\MiO::𝑂
: c?To:\MiP::𝑃
: c?To:\MiQ::𝑄
: c?To:\MiR::𝑅
: c?To:\MiS::𝑆
: c?To:\MiT::𝑇
: c?To:\MiU::𝑈
: c?To:\MiV::𝑉
: c?To:\MiW::𝑊
: c?To:\MiX::𝑋
: c?To:\MiY::𝑌
: c?To:\MiZ::𝑍
: c?To:\Mia::𝑎
: c?To:\Mib::𝑏
: c?To:\Mic::𝑐
: c?To:\Mid::𝑑
: c?To:\Mie::𝑒
: c?To:\Mif::𝑓
: c?To:\Mig::𝑔
: c?To:\Mih::𝘩
: c?To:\Mii::𝑖
: c?To:\Mij::𝑗
: c?To:\Mik::𝑘
: c?To:\Mil::𝑙
: c?To:\Mim::𝑚
: c?To:\Min::𝑛
: c?To:\Mio::𝑜
: c?To:\Mip::𝑝
: c?To:\Miq::𝑞
: c?To:\Mir::𝑟
: c?To:\Mis::𝑠
: c?To:\Mit::𝑡
: c?To:\Miu::𝑢
: c?To:\Miv::𝑣
: c?To:\Miw::𝑤
: c?To:\Mix::𝑥
: c?To:\Miy::𝑦
: c?To:\Miz::𝑧
: c?To:\McA::𝒜
: c?To:\McB::ℬ
: c?To:\McC::𝒞
: c?To:\McD::𝒟
: c?To:\McE::ℰ
: c?To:\McF::ℱ
: c?To:\McG::𝒢
: c?To:\McH::ℋ
: c?To:\McI::ℐ
: c?To:\McJ::𝒥
: c?To:\McK::𝒦
: c?To:\McL::ℒ
: c?To:\McM::ℳ
: c?To:\McN::𝒩
: c?To:\McO::𝒪
: c?To:\McP::𝒫
: c?To:\McQ::𝒬
: c?To:\McR::ℛ
: c?To:\McS::𝒮
: c?To:\McT::𝒯
: c?To:\McU::𝒰
: c?To:\McV::𝒱
: c?To:\McW::𝒲
: c?To:\McX::𝒳
: c?To:\McY::𝒴
: c?To:\McZ::𝒵
: c?To:\Mca::𝒶
: c?To:\Mcb::𝒷
: c?To:\Mcc::𝒸
: c?To:\Mcd::𝒹
: c?To:\Mce::ℯ
: c?To:\Mcf::𝒻
: c?To:\Mcg::ℊ
: c?To:\Mch::𝒽
: c?To:\Mci::𝒾
: c?To:\Mcj::𝒿
: c?To:\Mck::𝓀
: c?To:\Mcl::𝓁
: c?To:\Mcm::𝓂
: c?To:\Mcn::𝓃
: c?To:\Mco::ℴ
: c?To:\Mcp::𝓅
: c?To:\Mcq::𝓆
: c?To:\Mcr::𝓇
: c?To:\Mcs::𝓈
: c?To:\Mct::𝓉
: c?To:\Mcu::𝓊
: c?To:\Mcv::𝓋
: c?To:\Mcw::𝓌
: c?To:\Mcx::𝓍
: c?To:\Mcy::𝓎
: c?To:\Mcz::𝓏
: c?To:\MfA::𝔄
: c?To:\MfB::𝔅
: c?To:\MfC::ℭ
: c?To:\MfD::𝔇
: c?To:\MfE::𝔈
: c?To:\MfF::𝔉
: c?To:\MfG::𝔊
: c?To:\MfH::ℌ
: c?To:\MfI::ℑ
: c?To:\MfJ::𝔍
: c?To:\MfK::𝔎
: c?To:\MfL::𝔏
: c?To:\MfM::𝔐
: c?To:\MfN::𝔑
: c?To:\MfO::𝔒
: c?To:\MfP::𝔓
: c?To:\MfQ::𝔔
: c?To:\MfR::ℜ
: c?To:\MfS::𝔖
: c?To:\MfT::𝔗
: c?To:\MfU::𝔘
: c?To:\MfV::𝔙
: c?To:\MfW::𝔚
: c?To:\MfX::𝔛
: c?To:\MfY::𝔜
: c?To:\MfZ::ℨ
: c?To:\Mfa::𝔞
: c?To:\Mfb::𝔟
: c?To:\Mfc::𝔠
: c?To:\Mfd::𝔡
: c?To:\Mfe::𝔢
: c?To:\Mff::𝔣
: c?To:\Mfg::𝔤
: c?To:\Mfh::𝔥
: c?To:\Mfi::𝔦
: c?To:\Mfj::𝔧
: c?To:\Mfk::𝔨
: c?To:\Mfl::𝔩
: c?To:\Mfm::𝔪
: c?To:\Mfn::𝔫
: c?To:\Mfo::𝔬
: c?To:\Mfp::𝔭
: c?To:\Mfq::𝔮
: c?To:\Mfr::𝔯
: c?To:\Mfs::𝔰
: c?To:\Mft::𝔱
: c?To:\Mfu::𝔲
: c?To:\Mfv::𝔳
: c?To:\Mfw::𝔴
: c?To:\Mfx::𝔵
: c?To:\Mfy::𝔶
: c?To:\Mfz::𝔷